import mongoose from 'mongoose'
import dotenv from 'dotenv'
import User from './models/User.js'
import Post from './models/Post.js'
import Trainer from './models/Trainer.js'
import Comment from './models/Comment.js'
import connectDB from './config/db.js'

dotenv.config()

const seedDatabase = async () => {
  try {
    await connectDB()

    // Clear existing data
    await User.deleteMany({})
    await Post.deleteMany({})
    await Trainer.deleteMany({})
    await Comment.deleteMany({})

    console.log('Database cleared')

    // Create 20 sample users
    const users = await User.create([
      {
        name: 'Ahmed Khan',
        email: 'ahmed@fitsphere.com',
        password: 'password123',
        age: 28,
        gender: 'Male',
        weight: 75,
        height: 180,
        fitnessGoal: 'Muscle Gain',
        xp: 2500,
        level: 'Gold',
        streak: 15,
      },
      {
        name: 'Fatima Ali',
        email: 'fatima@fitsphere.com',
        password: 'password123',
        age: 26,
        gender: 'Female',
        weight: 65,
        height: 168,
        fitnessGoal: 'Weight Loss',
        xp: 3200,
        level: 'Platinum',
        streak: 22,
      },
      {
        name: 'Hassan Raza',
        email: 'hassan@fitsphere.com',
        password: 'password123',
        age: 32,
        gender: 'Male',
        weight: 82,
        height: 185,
        fitnessGoal: 'Muscle Gain',
        xp: 1800,
        level: 'Silver',
        streak: 10,
      },
      {
        name: 'Ayesha Malik',
        email: 'ayesha@fitsphere.com',
        password: 'password123',
        age: 24,
        gender: 'Female',
        weight: 58,
        height: 165,
        fitnessGoal: 'General Fitness',
        xp: 2100,
        level: 'Gold',
        streak: 12,
      },
      {
        name: 'Ali Saeed',
        email: 'ali@fitsphere.com',
        password: 'password123',
        age: 30,
        gender: 'Male',
        weight: 80,
        height: 182,
        fitnessGoal: 'Endurance',
        xp: 4500,
        level: 'Elite',
        streak: 35,
      },
      {
        name: 'Zainab Khan',
        email: 'zainab@fitsphere.com',
        password: 'password123',
        age: 27,
        gender: 'Female',
        weight: 62,
        height: 170,
        fitnessGoal: 'Flexibility',
        xp: 2300,
        level: 'Gold',
        streak: 18,
      },
      {
        name: 'Muhammad Hassan',
        email: 'mhassan@fitsphere.com',
        password: 'password123',
        age: 29,
        gender: 'Male',
        weight: 76,
        height: 178,
        fitnessGoal: 'Muscle Gain',
        xp: 1900,
        level: 'Silver',
        streak: 8,
      },
      {
        name: 'Sara Ahmed',
        email: 'sara@fitsphere.com',
        password: 'password123',
        age: 25,
        gender: 'Female',
        weight: 60,
        height: 166,
        fitnessGoal: 'Weight Loss',
        xp: 3100,
        level: 'Platinum',
        streak: 25,
      },
      {
        name: 'Imran Khan',
        email: 'imran@fitsphere.com',
        password: 'password123',
        age: 31,
        gender: 'Male',
        weight: 85,
        height: 186,
        fitnessGoal: 'Athletic Performance',
        xp: 2800,
        level: 'Gold',
        streak: 20,
      },
      {
        name: 'Hiba Noor',
        email: 'hiba@fitsphere.com',
        password: 'password123',
        age: 23,
        gender: 'Female',
        weight: 55,
        height: 162,
        fitnessGoal: 'General Fitness',
        xp: 1500,
        level: 'Bronze',
        streak: 5,
      },
      {
        name: 'Bilal Khalid',
        email: 'bilal@fitsphere.com',
        password: 'password123',
        age: 35,
        gender: 'Male',
        weight: 88,
        height: 188,
        fitnessGoal: 'Weight Loss',
        xp: 2600,
        level: 'Gold',
        streak: 16,
      },
      {
        name: 'Nida Rashid',
        email: 'nida@fitsphere.com',
        password: 'password123',
        age: 28,
        gender: 'Female',
        weight: 64,
        height: 169,
        fitnessGoal: 'Muscle Gain',
        xp: 2200,
        level: 'Silver',
        streak: 11,
      },
      {
        name: 'Samir Ahmed',
        email: 'samir@fitsphere.com',
        password: 'password123',
        age: 26,
        gender: 'Male',
        weight: 72,
        height: 176,
        fitnessGoal: 'General Fitness',
        xp: 1700,
        level: 'Bronze',
        streak: 7,
      },
      {
        name: 'Laiba Mirza',
        email: 'laiba@fitsphere.com',
        password: 'password123',
        age: 24,
        gender: 'Female',
        weight: 59,
        height: 167,
        fitnessGoal: 'Weight Loss',
        xp: 2950,
        level: 'Platinum',
        streak: 28,
      },
      {
        name: 'Tariq Hussain',
        email: 'tariq@fitsphere.com',
        password: 'password123',
        age: 33,
        gender: 'Male',
        weight: 84,
        height: 184,
        fitnessGoal: 'Bodybuilding',
        xp: 3400,
        level: 'Platinum',
        streak: 30,
      },
      {
        name: 'Amina Saeed',
        email: 'amina@fitsphere.com',
        password: 'password123',
        age: 29,
        gender: 'Female',
        weight: 63,
        height: 171,
        fitnessGoal: 'General Fitness',
        xp: 2000,
        level: 'Silver',
        streak: 14,
      },
      {
        name: 'Karim Abbas',
        email: 'karim@fitsphere.com',
        password: 'password123',
        age: 27,
        gender: 'Male',
        weight: 78,
        height: 179,
        fitnessGoal: 'Muscle Gain',
        xp: 2400,
        level: 'Gold',
        streak: 17,
      },
      {
        name: 'Dina Khan',
        email: 'dina@fitsphere.com',
        password: 'password123',
        age: 22,
        gender: 'Female',
        weight: 57,
        height: 164,
        fitnessGoal: 'Weight Loss',
        xp: 1300,
        level: 'Bronze',
        streak: 4,
      },
      {
        name: 'Naveed Ali',
        email: 'naveed@fitsphere.com',
        password: 'password123',
        age: 34,
        gender: 'Male',
        weight: 86,
        height: 187,
        fitnessGoal: 'Athletic Performance',
        xp: 3600,
        level: 'Elite',
        streak: 32,
      },
      {
        name: 'Rania Hassan',
        email: 'rania@fitsphere.com',
        password: 'password123',
        age: 30,
        gender: 'Female',
        weight: 66,
        height: 172,
        fitnessGoal: 'General Fitness',
        xp: 2700,
        level: 'Gold',
        streak: 19,
      },
    ])

    console.log(`✅ Created ${users.length} users`)

    // Create 8 trainers
    const trainers = await Trainer.create([
      {
        name: 'Coach Farhan',
        specialty: ['Fat Loss', "Women's Fitness"],
        experience: 8,
        certifications: ['ISSA CPT', 'NASM-CES'],
        rating: 4.8,
        reviews: 156,
        hourlyRate: 50,
        bio: 'Specializes in weight loss transformations',
        image: 'https://i.pravatar.cc/150?img=12',
      },
      {
        name: 'Coach Adnan',
        specialty: ['Bodybuilding', 'Muscle Gain'],
        experience: 12,
        certifications: ['IFBB Pro', 'ACE'],
        rating: 4.9,
        reviews: 289,
        hourlyRate: 75,
        bio: 'Former bodybuilding champion',
        image: 'https://i.pravatar.cc/150?img=33',
      },
      {
        name: 'Coach Zara',
        specialty: ["Women's Fitness", 'Nutrition'],
        experience: 6,
        certifications: ['ISSN-SNS', 'NASM'],
        rating: 4.7,
        reviews: 98,
        hourlyRate: 45,
        bio: 'Women fitness and nutrition expert',
        image: 'https://i.pravatar.cc/150?img=47',
      },
      {
        name: 'Coach Rashid',
        specialty: ['Powerlifting', 'Sports Performance'],
        experience: 15,
        certifications: ['IPF Judge', 'USAW'],
        rating: 4.9,
        reviews: 342,
        hourlyRate: 80,
        bio: 'Olympic lifting and strength coach',
        image: 'https://i.pravatar.cc/150?img=22',
      },
      {
        name: 'Coach Leila',
        specialty: ['Fat Loss', 'General Fitness'],
        experience: 7,
        certifications: ['ISSA', 'ACE-GFI'],
        rating: 4.6,
        reviews: 124,
        hourlyRate: 40,
        bio: 'Holistic fitness approach trainer',
        image: 'https://i.pravatar.cc/150?img=69',
      },
      {
        name: 'Coach Sameer',
        specialty: ['Sports Performance', 'Athletic Training'],
        experience: 10,
        certifications: ['CSCS', 'USAW'],
        rating: 4.8,
        reviews: 201,
        hourlyRate: 70,
        bio: 'Sports performance specialist',
        image: 'https://i.pravatar.cc/150?img=15',
      },
      {
        name: 'Coach Amira',
        specialty: ['Nutrition', "Women's Fitness"],
        experience: 9,
        certifications: ['ISSN-SNS', 'NASM-CES'],
        rating: 4.7,
        reviews: 167,
        hourlyRate: 55,
        bio: 'Nutrition and wellness coach',
        image: 'https://i.pravatar.cc/150?img=91',
      },
      {
        name: 'Coach Ibrahim',
        specialty: ['Bodybuilding', 'Muscle Gain'],
        experience: 11,
        certifications: ['IFBB Pro Card', 'ACE'],
        rating: 4.9,
        reviews: 267,
        hourlyRate: 70,
        bio: 'Muscle building and bodybuilding expert',
        image: 'https://i.pravatar.cc/150?img=44',
      },
    ])

    console.log(`✅ Created ${trainers.length} trainers`)

    // Create 30 community posts
    const posts = await Post.create(
      Array.from({ length: 30 }, (_, i) => ({
        author: users[i % users.length]._id,
        title: [
          'Just completed my 100th workout! 💪',
          'Finally hit my target weight!',
          'New PR on bench press today',
          'Started my fitness journey today',
          'Tips for staying consistent with workouts',
          'Meal prep Sunday done! 🥗',
          'Recovery is just as important as training',
          'Before and after - 3 months progress',
          'Morning run in the park',
          'Yoga transformed my flexibility',
          'Intermittent fasting results after 1 month',
          'How I overcame my fitness plateau',
          'Best HIIT workout ever!',
          'Strength training at 5 AM',
          'My favorite healthy recipes',
          'Rest day activities that help recovery',
          'Hydration tips for athletes',
          'Building your home gym on a budget',
          'Fitness motivation playlist',
          'How to stay fit while traveling',
          'Women empowerment in fitness spaces',
          'Mental health benefits of exercise',
          'Overcoming gym anxiety',
          'Setting realistic fitness goals',
          'Time management for busy fitness enthusiasts',
          'Supplement review and recommendations',
          'Injury prevention tips',
          'Getting back to fitness after layoff',
          'My fitness transformation story',
          'Community workout challenge results',
        ][i % 30],
        description: [
          'Feeling amazing after hitting this milestone! The consistency finally paid off.',
          'After 6 months of dedication, I finally reached my goal weight!',
          'New personal record - lifted 100kg for the first time! #Progress',
          'Starting my fitness journey at 25. Excited to transform my body and health!',
          'Consistency beats intensity. Work out 4-5 times a week at moderate intensity.',
          'Prepped meals for the entire week. Eating clean makes everything easier!',
          'Sleep and rest days are when your body actually builds muscle. Don\'t skip them!',
          'Look at this progress! 90 days of consistent training and clean eating.',
          'Morning runs are the best way to start the day. Energy for the whole day!',
          'From zero flexibility to touching my toes. Yoga is a game changer!',
          'Lost 8kg in a month with intermittent fasting. Highly recommend!',
          'Hit a plateau for 3 months. Then I switched my routine and boom - progress!',
          'This 30-minute HIIT workout destroyed me in the best way possible.',
          'Nothing beats early morning training when the gym is empty and quiet.',
          'Sharing my favorite healthy recipes that taste amazing and are nutritious.',
          'Rest days are not lazy days. They\'re essential for recovery and growth.',
          'Drinking 3-4 liters of water daily changed my workout performance completely.',
          'You don\'t need a fancy gym. Dumbbells, barbells, and bench - that\'s all!',
          'Music is crucial for my workouts. Check out my playlist!',
          'Stayed consistent while traveling. You can do it anywhere!',
          'More women are joining gyms and breaking stereotypes. Love to see it!',
          'Exercise isn\'t just physical. The mental health benefits are incredible.',
          'Used to be scared of the gym. Now it\'s my happy place!',
          'SMART goals work! Specific, Measurable, Achievable, Relevant, Time-bound.',
          'Wake up at 5 AM, workout, then tackle the day. Game changer for productivity.',
          'Tested 5 supplements. Here are my honest reviews.',
          'Listen to your body. Pain is not weakness leaving the body - it\'s injury.',
          'Three months off due to injury. Back to 50% strength. Progress takes time.',
          'Down 25kg, up 10kg of muscle. This is what transformation looks like!',
          'Amazing turnout for our community challenge! Results are incredible!',
        ][i % 30],
        image: [
          'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=500',
          'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500',
          'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=500',
          'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
          'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500',
          'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500',
          'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=500',
          'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
          'https://images.unsplash.com/photo-1475921917321-8188e6a9c254?w=500',
          'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500',
          'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=500',
          'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500',
          'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=500',
          'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500',
          'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500',
          'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500',
          'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=500',
          'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500',
          'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500',
          'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500',
          'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
          'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=500',
          'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500',
          'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500',
          'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500',
          'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=500',
          'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500',
          'https://images.unsplash.com/photo-1517836357463-d25ddfcbf042?w=500',
          'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500',
          'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=500',
        ][i % 30],
        likesCount: Math.floor(Math.random() * 200) + 10,
        commentsCount: Math.floor(Math.random() * 50) + 5,
      }))
    )

    console.log(`✅ Created ${posts.length} posts`)

    console.log('✅ Database seeded successfully!')
    process.exit(0)
  } catch (error) {
    console.error('Error seeding database:', error)
    process.exit(1)
  }
}

seedDatabase()
